services:

    #
    # Plugin
    #
    elcodi_plugin.stripe:
        parent: elcodi.abstract_plugin
        arguments:
            - "Elcodi\\Plugin\\StripeBundle\\ElcodiStripeBundle"

    stripe.transaction.wrapper:
        class: %stripe.transaction.wrapper.class%
        arguments:
            - "@elcodi_plugin.stripe.private_key"

    #
    # Plugin fields
    #
    elcodi_plugin.stripe.public_key:
        class: StdClass
        factory:
            - "@elcodi_plugin.stripe"
            - getFieldValue
        arguments:
            - public_key

    elcodi_plugin.stripe.private_key:
        class: StdClass
        factory:
            - "@elcodi_plugin.stripe"
            - getFieldValue
        arguments:
            - private_key

    #
    # Services
    #
    stripe.twig.extension:
        class: %stripe.twig.extension.class%
        lazy: true
        arguments:
            - "@elcodi_plugin.stripe.public_key"
            - "@form.factory"
            - "@payment.bridge"
            - %stripe.templates.view_template%
            - %stripe.templates.scripts_template%
        tags:
            - { name: twig.extension }
